CREATE TABLE [dbo].[ZeModel](
	[Id] [bigint] NOT NULL,
	[Text] [nvarchar](max) NULL,
 CONSTRAINT [PK_ZeModel] PRIMARY KEY CLUSTERED
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
